logging:
  level:
    root: info
    com.yax.messagequeue: info
  //path: /www/server/apache-tomcat-8.5.32/logs/messagequeue
  path: /usr/tomcat9/logs/messagequeue
  config:
    classpath:logback-spring.xml
server:
  #context-path: /messagequeue
  session-timeout: 1800
  #    tomcat:
  #        max-threads: 1000
  #        min-spare-threads: 30
  port: 8082
#    uri-encoding: utf-8
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  jmx:
    enabled: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        # \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5927\u7A7A\u95F2\u8FDE\u63A5
        max-idle: 5
        # \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5
        min-idle: 3
        # \u8FDE\u63A5\u6C60\u6700\u5927\u8FDE\u63A5\u6570\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
        max-active: 8
        # \u8FDE\u63A5\u6C60\u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
        max-wait: 3000
    # \u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4\uFF08\u6BEB\u79D2\uFF09
    timeout: 60000
quartz:
  listener:
    # cron表达式 默认1分钟执行一次
    cron: /10 * * * * ?
netty:
  server:
    openWhiteList: false
    maxLength: 10240
